/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { BuildableResponse } from '../model/buildableResponse';
import { Disable2FARequest } from '../model/disable2FARequest';
import { Enable2FARequest } from '../model/enable2FARequest';
import { LoginProperties } from '../model/loginProperties';
import { LoginPropertiesCopy } from '../model/loginPropertiesCopy';
import { PrepareComponent } from '../model/prepareComponent';
import { QRImageUrlResponse } from '../model/qRImageUrlResponse';
import { RestResourceInfo } from '../model/restResourceInfo';
import { TagName } from '../model/tagName';
import { User } from '../model/user';
import { Verify2FA } from '../model/verify2FA';
import { WebMessage } from '../model/webMessage';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class UserResourceService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Activate the user
     * Activate the user and returns it if all went ok, else 500 is thrown
     * @param websiteId websiteId
     * @param activationToken activationToken
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public activateUserUsingGET(websiteId: number, activationToken: string, observe?: 'body', reportProgress?: boolean): Observable<User>;
    public activateUserUsingGET(websiteId: number, activationToken: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<User>>;
    public activateUserUsingGET(websiteId: number, activationToken: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<User>>;
    public activateUserUsingGET(websiteId: number, activationToken: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (websiteId === null || websiteId === undefined) {
            throw new Error('Required parameter websiteId was null or undefined when calling activateUserUsingGET.');
        }
        if (activationToken === null || activationToken === undefined) {
            throw new Error('Required parameter activationToken was null or undefined when calling activateUserUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<User>(`${this.basePath}/user/activate/${encodeURIComponent(String(websiteId))}/${encodeURIComponent(String(activationToken))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Prepare the login module for preview or creation
     * Prepare the login module for preview or creation
     * @param prepareComponent prepareComponent
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public buildUsingPOST(prepareComponent: PrepareComponent, observe?: 'body', reportProgress?: boolean): Observable<BuildableResponse>;
    public buildUsingPOST(prepareComponent: PrepareComponent, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BuildableResponse>>;
    public buildUsingPOST(prepareComponent: PrepareComponent, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BuildableResponse>>;
    public buildUsingPOST(prepareComponent: PrepareComponent, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (prepareComponent === null || prepareComponent === undefined) {
            throw new Error('Required parameter prepareComponent was null or undefined when calling buildUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<BuildableResponse>(`${this.basePath}/user/prepare`,
            prepareComponent,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Copy the login properties fragments by ID
     * Returns the new copied fragments
     * @param search search
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public copyPropertiesUsingPOST(search: LoginPropertiesCopy, observe?: 'body', reportProgress?: boolean): Observable<Array<LoginProperties>>;
    public copyPropertiesUsingPOST(search: LoginPropertiesCopy, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<LoginProperties>>>;
    public copyPropertiesUsingPOST(search: LoginPropertiesCopy, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<LoginProperties>>>;
    public copyPropertiesUsingPOST(search: LoginPropertiesCopy, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (search === null || search === undefined) {
            throw new Error('Required parameter search was null or undefined when calling copyPropertiesUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<Array<LoginProperties>>(`${this.basePath}/user/copy`,
            search,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete the user by ID
     * Deletes the user, returns a boolean
     * @param search search
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteFragmentUsingPOST(search: User, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public deleteFragmentUsingPOST(search: User, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public deleteFragmentUsingPOST(search: User, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public deleteFragmentUsingPOST(search: User, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (search === null || search === undefined) {
            throw new Error('Required parameter search was null or undefined when calling deleteFragmentUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<boolean>(`${this.basePath}/user/delete`,
            search,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete the component property by ID
     * Deletes the component property, returns a boolean
     * @param search search
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deletePropertiesUsingPOST(search: LoginProperties, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public deletePropertiesUsingPOST(search: LoginProperties, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public deletePropertiesUsingPOST(search: LoginProperties, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public deletePropertiesUsingPOST(search: LoginProperties, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (search === null || search === undefined) {
            throw new Error('Required parameter search was null or undefined when calling deletePropertiesUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<boolean>(`${this.basePath}/user/deleteProperty`,
            search,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Enable 2fa
     * Enable 2FA on user
     * @param faRequest faRequest
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public disable2FAUsingPOST(faRequest: Disable2FARequest, observe?: 'body', reportProgress?: boolean): Observable<User>;
    public disable2FAUsingPOST(faRequest: Disable2FARequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<User>>;
    public disable2FAUsingPOST(faRequest: Disable2FARequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<User>>;
    public disable2FAUsingPOST(faRequest: Disable2FARequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (faRequest === null || faRequest === undefined) {
            throw new Error('Required parameter faRequest was null or undefined when calling disable2FAUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<User>(`${this.basePath}/user/disable2FA`,
            faRequest,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Enable 2fa
     * Enable 2FA on user
     * @param faRequest faRequest
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public enable2FAUsingPOST(faRequest: Enable2FARequest, observe?: 'body', reportProgress?: boolean): Observable<User>;
    public enable2FAUsingPOST(faRequest: Enable2FARequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<User>>;
    public enable2FAUsingPOST(faRequest: Enable2FARequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<User>>;
    public enable2FAUsingPOST(faRequest: Enable2FARequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (faRequest === null || faRequest === undefined) {
            throw new Error('Required parameter faRequest was null or undefined when calling enable2FAUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<User>(`${this.basePath}/user/enable2FA`,
            faRequest,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Activate the user
     * Activate the user and returns it if all went ok, else 500 is thrown
     * @param user user
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public forgotPasswordUsingPOST(user: User, observe?: 'body', reportProgress?: boolean): Observable<WebMessage>;
    public forgotPasswordUsingPOST(user: User, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<WebMessage>>;
    public forgotPasswordUsingPOST(user: User, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<WebMessage>>;
    public forgotPasswordUsingPOST(user: User, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (user === null || user === undefined) {
            throw new Error('Required parameter user was null or undefined when calling forgotPasswordUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<WebMessage>(`${this.basePath}/user/forgotPassword`,
            user,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the form of the properties
     * Returns the form of the properties
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFormSkeletonUsingGET(observe?: 'body', reportProgress?: boolean): Observable<string>;
    public getFormSkeletonUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public getFormSkeletonUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public getFormSkeletonUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<string>(`${this.basePath}/user/formSkeleton`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the html exposed tags
     * Get the tag names that can be used in the pages
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getHtmlTagsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<TagName>>;
    public getHtmlTagsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TagName>>>;
    public getHtmlTagsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TagName>>>;
    public getHtmlTagsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<TagName>>(`${this.basePath}/user/exposedTags`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns the skeleton of the properties
     * Returns the skeleton of the properties that can be saved by the service to use later
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPropertiesSkeletonUsingGET(observe?: 'body', reportProgress?: boolean): Observable<string>;
    public getPropertiesSkeletonUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public getPropertiesSkeletonUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public getPropertiesSkeletonUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<string>(`${this.basePath}/user/propertiesSkeleton`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the login properties
     * Get the login properties for a site and returns it if all went ok, else 500 is thrown
     * @param website website
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPropertiesUsingPOST(website: LoginProperties, observe?: 'body', reportProgress?: boolean): Observable<LoginProperties>;
    public getPropertiesUsingPOST(website: LoginProperties, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoginProperties>>;
    public getPropertiesUsingPOST(website: LoginProperties, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoginProperties>>;
    public getPropertiesUsingPOST(website: LoginProperties, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (website === null || website === undefined) {
            throw new Error('Required parameter website was null or undefined when calling getPropertiesUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<LoginProperties>(`${this.basePath}/user/getProperties`,
            website,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Is the Service running ?
     * Returns if the service runs or not. Without other exceptions in mind, just running
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getResourceInfoUsingGET1(observe?: 'body', reportProgress?: boolean): Observable<RestResourceInfo>;
    public getResourceInfoUsingGET1(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RestResourceInfo>>;
    public getResourceInfoUsingGET1(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RestResourceInfo>>;
    public getResourceInfoUsingGET1(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<RestResourceInfo>(`${this.basePath}/user/info`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find the user by ID
     * Returns the user for the given ID.
     * @param search search
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public loginUsingPOST(search: User, observe?: 'body', reportProgress?: boolean): Observable<User>;
    public loginUsingPOST(search: User, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<User>>;
    public loginUsingPOST(search: User, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<User>>;
    public loginUsingPOST(search: User, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (search === null || search === undefined) {
            throw new Error('Required parameter search was null or undefined when calling loginUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<User>(`${this.basePath}/user/login`,
            search,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Refresh the JWT Token
     * Based on the refresh token if it passed the JWTFilter
     * @param search search
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public refreshUsingPOST(search: User, observe?: 'body', reportProgress?: boolean): Observable<User>;
    public refreshUsingPOST(search: User, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<User>>;
    public refreshUsingPOST(search: User, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<User>>;
    public refreshUsingPOST(search: User, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (search === null || search === undefined) {
            throw new Error('Required parameter search was null or undefined when calling refreshUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<User>(`${this.basePath}/user/refresh`,
            search,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Register the user
     * Register the user and returns it if all went ok, else 500 is thrown
     * @param fragment fragment
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public registerUsingPOST(fragment: User, observe?: 'body', reportProgress?: boolean): Observable<User>;
    public registerUsingPOST(fragment: User, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<User>>;
    public registerUsingPOST(fragment: User, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<User>>;
    public registerUsingPOST(fragment: User, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (fragment === null || fragment === undefined) {
            throw new Error('Required parameter fragment was null or undefined when calling registerUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<User>(`${this.basePath}/user/register`,
            fragment,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Request a QR code to enable 2fa
     * Request a QR code to enable 2fa, returns a QRImageUrlResponseEntity
     * @param user user
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public requestEnable2FAUsingPOST(user: User, observe?: 'body', reportProgress?: boolean): Observable<QRImageUrlResponse>;
    public requestEnable2FAUsingPOST(user: User, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<QRImageUrlResponse>>;
    public requestEnable2FAUsingPOST(user: User, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<QRImageUrlResponse>>;
    public requestEnable2FAUsingPOST(user: User, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (user === null || user === undefined) {
            throw new Error('Required parameter user was null or undefined when calling requestEnable2FAUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<QRImageUrlResponse>(`${this.basePath}/user/requestEnable2FA`,
            user,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Reset password
     * Reset password and returns the user if all went ok, else 500 is thrown
     * @param websiteId websiteId
     * @param passwordResetToken passwordResetToken
     * @param password password
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public resetPasswordUsingPOST(websiteId: number, passwordResetToken: string, password: User, observe?: 'body', reportProgress?: boolean): Observable<User>;
    public resetPasswordUsingPOST(websiteId: number, passwordResetToken: string, password: User, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<User>>;
    public resetPasswordUsingPOST(websiteId: number, passwordResetToken: string, password: User, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<User>>;
    public resetPasswordUsingPOST(websiteId: number, passwordResetToken: string, password: User, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (websiteId === null || websiteId === undefined) {
            throw new Error('Required parameter websiteId was null or undefined when calling resetPasswordUsingPOST.');
        }
        if (passwordResetToken === null || passwordResetToken === undefined) {
            throw new Error('Required parameter passwordResetToken was null or undefined when calling resetPasswordUsingPOST.');
        }
        if (password === null || password === undefined) {
            throw new Error('Required parameter password was null or undefined when calling resetPasswordUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<User>(`${this.basePath}/user/resetPassword/${encodeURIComponent(String(websiteId))}/${encodeURIComponent(String(passwordResetToken))}`,
            password,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Save the login properties
     * Save the login properties and returns it if all went ok, else 500 is thrown
     * @param website website
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public savePropertiesUsingPOST(website: LoginProperties, observe?: 'body', reportProgress?: boolean): Observable<LoginProperties>;
    public savePropertiesUsingPOST(website: LoginProperties, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoginProperties>>;
    public savePropertiesUsingPOST(website: LoginProperties, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoginProperties>>;
    public savePropertiesUsingPOST(website: LoginProperties, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (website === null || website === undefined) {
            throw new Error('Required parameter website was null or undefined when calling savePropertiesUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<LoginProperties>(`${this.basePath}/user/saveProperties`,
            website,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update the user
     * Update the user and returns it if all went ok, else 500 is thrown
     * @param fragment fragment
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateFragmentUsingPOST(fragment: User, observe?: 'body', reportProgress?: boolean): Observable<User>;
    public updateFragmentUsingPOST(fragment: User, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<User>>;
    public updateFragmentUsingPOST(fragment: User, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<User>>;
    public updateFragmentUsingPOST(fragment: User, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (fragment === null || fragment === undefined) {
            throw new Error('Required parameter fragment was null or undefined when calling updateFragmentUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<User>(`${this.basePath}/user/update`,
            fragment,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Save the login properties
     * Save the login properties and returns it if all went ok, else 500 is thrown
     * @param website website
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updatePropertiesUsingPOST(website: LoginProperties, observe?: 'body', reportProgress?: boolean): Observable<LoginProperties>;
    public updatePropertiesUsingPOST(website: LoginProperties, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LoginProperties>>;
    public updatePropertiesUsingPOST(website: LoginProperties, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LoginProperties>>;
    public updatePropertiesUsingPOST(website: LoginProperties, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (website === null || website === undefined) {
            throw new Error('Required parameter website was null or undefined when calling updatePropertiesUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<LoginProperties>(`${this.basePath}/user/updateProperties`,
            website,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Validate the login module for preview or creation
     * Validate the login module for preview or creation
     * @param prepareComponent prepareComponent
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public validateUsingPOST(prepareComponent: PrepareComponent, observe?: 'body', reportProgress?: boolean): Observable<PrepareComponent>;
    public validateUsingPOST(prepareComponent: PrepareComponent, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PrepareComponent>>;
    public validateUsingPOST(prepareComponent: PrepareComponent, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PrepareComponent>>;
    public validateUsingPOST(prepareComponent: PrepareComponent, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (prepareComponent === null || prepareComponent === undefined) {
            throw new Error('Required parameter prepareComponent was null or undefined when calling validateUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<PrepareComponent>(`${this.basePath}/user/validate`,
            prepareComponent,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Verifies the 2fa number
     * Verifies the 2fa number, returns a User
     * @param search search
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public verify2FAUsingPOST(search: Verify2FA, observe?: 'body', reportProgress?: boolean): Observable<User>;
    public verify2FAUsingPOST(search: Verify2FA, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<User>>;
    public verify2FAUsingPOST(search: Verify2FA, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<User>>;
    public verify2FAUsingPOST(search: Verify2FA, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (search === null || search === undefined) {
            throw new Error('Required parameter search was null or undefined when calling verify2FAUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<User>(`${this.basePath}/user/verify2FA`,
            search,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
