/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { AddressBalance } from '../model/addressBalance';
import { BlockOrTransactionRequest } from '../model/blockOrTransactionRequest';
import { BlockOrTransactionResponse } from '../model/blockOrTransactionResponse';
import { BlockWrapper } from '../model/blockWrapper';
import { Payment } from '../model/payment';
import { PaymentInput } from '../model/paymentInput';
import { RestResourceInfo } from '../model/restResourceInfo';
import { Success } from '../model/success';
import { TransactionsResponse } from '../model/transactionsResponse';
import { UserAddress } from '../model/userAddress';
import { WalletCoin } from '../model/walletCoin';
import { WalletKeys } from '../model/walletKeys';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class WalletService {

    protected basePath = 'https://api.b2bcoin.xyz/b2bcoin/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Find the component fragment by ID
     * Returns the fragments for the given ID. It&#39;s a composite ID, so it is used as criteria
     * @param coinType 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createAddress(coinType: string, observe?: 'body', reportProgress?: boolean): Observable<UserAddress>;
    public createAddress(coinType: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserAddress>>;
    public createAddress(coinType: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserAddress>>;
    public createAddress(coinType: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (coinType === null || coinType === undefined) {
            throw new Error('Required parameter coinType was null or undefined when calling createAddress.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<UserAddress>(`${this.basePath}/wallet/createAddress/${encodeURIComponent(String(coinType))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create a payment
     * Create a payment and return the hash of it.
     * @param coinType 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createPayment(coinType: string, body?: PaymentInput, observe?: 'body', reportProgress?: boolean): Observable<Payment>;
    public createPayment(coinType: string, body?: PaymentInput, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Payment>>;
    public createPayment(coinType: string, body?: PaymentInput, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Payment>>;
    public createPayment(coinType: string, body?: PaymentInput, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (coinType === null || coinType === undefined) {
            throw new Error('Required parameter coinType was null or undefined when calling createPayment.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<Payment>(`${this.basePath}/wallet/createPayment/${encodeURIComponent(String(coinType))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find the component fragment by ID
     * Returns the fragments for the given ID. It&#39;s a composite ID, so it is used as criteria
     * @param coinType 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteAddress(coinType: string, body?: UserAddress, observe?: 'body', reportProgress?: boolean): Observable<Success>;
    public deleteAddress(coinType: string, body?: UserAddress, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Success>>;
    public deleteAddress(coinType: string, body?: UserAddress, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Success>>;
    public deleteAddress(coinType: string, body?: UserAddress, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (coinType === null || coinType === undefined) {
            throw new Error('Required parameter coinType was null or undefined when calling deleteAddress.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<Success>(`${this.basePath}/wallet/deleteAddress/${encodeURIComponent(String(coinType))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find the component fragment by ID
     * Returns the fragments for the given ID. It&#39;s a composite ID, so it is used as criteria
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAddresses(observe?: 'body', reportProgress?: boolean): Observable<Array<UserAddress>>;
    public getAddresses(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<UserAddress>>>;
    public getAddresses(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<UserAddress>>>;
    public getAddresses(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<UserAddress>>(`${this.basePath}/wallet/getAddresses`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find the component fragment by ID
     * Returns the fragments for the given ID. It&#39;s a composite ID, so it is used as criteria
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getBalance(body?: UserAddress, observe?: 'body', reportProgress?: boolean): Observable<AddressBalance>;
    public getBalance(body?: UserAddress, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AddressBalance>>;
    public getBalance(body?: UserAddress, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AddressBalance>>;
    public getBalance(body?: UserAddress, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<AddressBalance>(`${this.basePath}/wallet/getBalance`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find the block or transaction in the coin daemon by hash
     * Returns the block or the transaction for the given hash.
     * @param coinType 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getBlockOrTransaction(coinType: string, body?: BlockOrTransactionRequest, observe?: 'body', reportProgress?: boolean): Observable<BlockOrTransactionResponse>;
    public getBlockOrTransaction(coinType: string, body?: BlockOrTransactionRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BlockOrTransactionResponse>>;
    public getBlockOrTransaction(coinType: string, body?: BlockOrTransactionRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BlockOrTransactionResponse>>;
    public getBlockOrTransaction(coinType: string, body?: BlockOrTransactionRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (coinType === null || coinType === undefined) {
            throw new Error('Required parameter coinType was null or undefined when calling getBlockOrTransaction.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<BlockOrTransactionResponse>(`${this.basePath}/wallet/getBlockOrTransaction/${encodeURIComponent(String(coinType))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get supported coins
     * Returns the coins supported by the wallet
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCoinTypes(observe?: 'body', reportProgress?: boolean): Observable<Array<WalletCoin>>;
    public getCoinTypes(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<WalletCoin>>>;
    public getCoinTypes(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<WalletCoin>>>;
    public getCoinTypes(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<WalletCoin>>(`${this.basePath}/wallet/getCoinTypes`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find the component fragment by ID
     * Returns the fragments for the given ID. It&#39;s a composite ID, so it is used as criteria
     * @param coinType 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLastBlock(coinType: string, observe?: 'body', reportProgress?: boolean): Observable<BlockWrapper>;
    public getLastBlock(coinType: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<BlockWrapper>>;
    public getLastBlock(coinType: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<BlockWrapper>>;
    public getLastBlock(coinType: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (coinType === null || coinType === undefined) {
            throw new Error('Required parameter coinType was null or undefined when calling getLastBlock.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<BlockWrapper>(`${this.basePath}/wallet/getLastBlock/${encodeURIComponent(String(coinType))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Is the Service running ?
     * Returns if the service runs or not. Without other exceptions in mind, just running
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getResourceInfo(observe?: 'body', reportProgress?: boolean): Observable<RestResourceInfo>;
    public getResourceInfo(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RestResourceInfo>>;
    public getResourceInfo(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RestResourceInfo>>;
    public getResourceInfo(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<RestResourceInfo>(`${this.basePath}/wallet/info`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the spendKeys for a userAddress
     * Returns the public view key and the private spend key
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSpendKeys(body?: UserAddress, observe?: 'body', reportProgress?: boolean): Observable<WalletKeys>;
    public getSpendKeys(body?: UserAddress, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<WalletKeys>>;
    public getSpendKeys(body?: UserAddress, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<WalletKeys>>;
    public getSpendKeys(body?: UserAddress, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<WalletKeys>(`${this.basePath}/wallet/getSpendKeys`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find the transactions for the address
     * Find the transactions for the address.
     * @param coinType 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTransactionsForAddress(coinType: string, body?: UserAddress, observe?: 'body', reportProgress?: boolean): Observable<TransactionsResponse>;
    public getTransactionsForAddress(coinType: string, body?: UserAddress, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TransactionsResponse>>;
    public getTransactionsForAddress(coinType: string, body?: UserAddress, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TransactionsResponse>>;
    public getTransactionsForAddress(coinType: string, body?: UserAddress, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (coinType === null || coinType === undefined) {
            throw new Error('Required parameter coinType was null or undefined when calling getTransactionsForAddress.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<TransactionsResponse>(`${this.basePath}/wallet/getTransactionsForAddress/${encodeURIComponent(String(coinType))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
