/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FormInput } from './formInput';
import { SelectValue } from './selectValue';


export interface LoginProperties {
    websiteId?: number;
    websiteLoginDivId?: string;
    websiteRegisterDivId?: string;
    websiteForgotPasswordDivId?: string;
    loginPropertyOrText?: string;
    registerPropertyOrText?: string;
    forgotPasswordPropertyOrText?: string;
    dialog?: boolean;
    dialogWidthClasses?: Array<SelectValue>;
    dialogWidthClass?: string;
    linksAsButton?: boolean;
    confirmationNeeded?: boolean;
    decisionMakerMail?: string;
    confirmationMail?: string;
    usernameNeeded?: boolean;
    addressNeeded?: boolean;
    enableVAT?: boolean;
    enableVATValidation?: boolean;
    numberOfShopsNeeded?: boolean;
    numberOfShopsNeededPerCountry?: boolean;
    revenuesNeeded?: boolean;
    form?: Array<FormInput>;
}
