/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface User {
    websiteId?: number;

    userId?: string;

    password?: string;

    salt?: string;

    secretKey?: string;

    active?: boolean;

    passwordResetToken?: string;

    activationToken?: string;

    ip?: string;

    authenticationToken?: string;

    authenticationRefreshToken?: string;

    userDetails?: models.UserDetails;

    enabled2FA?: boolean;

    code2FA?: number;

    valid?: boolean;

}
