/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface FormInput {
    disabled?: boolean;
    hidden?: boolean;
    id?: string;
    ifStatement?: string;
    key?: string;
    name?: string;
    pattern?: string;
    placeHolder?: string;
    required?: boolean;
    title?: string;
    type?: string;
}
