/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FormInput } from './formInput';
import { SelectValue } from './selectValue';


export interface LoginProperties {
    addressNeeded?: boolean;
    confirmationMail?: string;
    confirmationNeeded?: boolean;
    decisionMakerMail?: string;
    dialog?: boolean;
    dialogWidthClass?: string;
    dialogWidthClasses?: Array<SelectValue>;
    enableVAT?: boolean;
    enableVATValidation?: boolean;
    forgotPasswordPropertyOrText?: string;
    form?: Array<FormInput>;
    linksAsButton?: boolean;
    loginPropertyOrText?: string;
    numberOfShopsNeeded?: boolean;
    numberOfShopsNeededPerCountry?: boolean;
    registerPropertyOrText?: string;
    revenuesNeeded?: boolean;
    usernameNeeded?: boolean;
    websiteForgotPasswordDivId?: string;
    websiteId?: number;
    websiteLoginDivId?: string;
    websiteRegisterDivId?: string;
}
