/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LoginProperties } from './loginProperties';
import { Translation } from './translation';


export interface PrepareComponent {
    content?: string;
    dataSets?: { [key: string]: string; };
    preview?: boolean;
    properties?: LoginProperties;
    translations?: Array<Translation>;
}
