/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Block {
    alreadyGeneratedCoins?: number;

    alreadyGeneratedTransactions?: number;

    baseReward?: number;

    blockSize?: number;

    depth?: number;

    difficulty?: number;

    hash?: string;

    height?: number;

    majorVersion?: number;

    minorVersion?: number;

    nonce?: number;

    orphanStatus?: boolean;

    penalty?: number;

    prevHash?: string;

    reward?: number;

    sizeMedian?: number;

    timestamp?: number;

    totalFeeAmount?: number;

    transactions?: Array<models.BlockTransaction>;

    transactionsCumulativeSize?: number;

}
