/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface EscrowTransaction {
    transactionKey?: string;

    sellEmail?: string;

    buyEmail?: string;

    startTransaction?: Date;

    endTransaction?: Date;

    sellCoinType?: string;

    sellAddress?: string;

    sellAmount?: number;

    sellConfirmed?: boolean;

    sellReceived?: boolean;

    buyStartTransaction?: Date;

    buyEndTransaction?: Date;

    buyCoinType?: string;

    buyAddress?: string;

    buyAmount?: number;

    buyConfirmed?: boolean;

    buyReceived?: boolean;

    intermediateSellAddress?: string;

    intermediateBuyAddress?: string;

    locked?: boolean;

    totalSellAmount?: number;

    totalBuyAmount?: number;

}
