/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface PaymentInput {
    addresses?: Array<models.Address>;

    transfers?: { [key: string]: number; };

    fee?: number;

    unlockTime?: number;

    anonymity?: number;

    paymentId?: string;

    address?: string;

    params?: string;

}
