/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressBalance } from './addressBalance';
import { ApiKeys } from './apiKeys';
import { UserAddressPK } from './userAddressPK';
import { WalletCoin } from './walletCoin';


export interface UserAddress {
    pairPk?: UserAddressPK;
    userId?: string;
    address?: string;
    faucet?: boolean;
    faucetUser?: boolean;
    currency?: WalletCoin;
    name?: string;
    faucetUrl?: string;
    groupName?: string;
    paymentId?: string;
    balance?: AddressBalance;
    faucetPaidBalance?: AddressBalance;
    apiKeys?: ApiKeys;
    key?: UserAddressPK;
}
