/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CreateFaucetAddressRequest } from '../model/createFaucetAddressRequest';
import { FaucetAddressPayment } from '../model/faucetAddressPayment';
import { FaucetAddressRequest } from '../model/faucetAddressRequest';
import { FaucetBalanceRequest } from '../model/faucetBalanceRequest';
import { FaucetPaymentRequest } from '../model/faucetPaymentRequest';
import { RestResourceInfo } from '../model/restResourceInfo';
import { ResultOk } from '../model/resultOk';
import { UserAddress } from '../model/userAddress';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class FaucetResourceService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * create faucet address
     * Creates a faucet address and returns it
     * @param createFaucetAddressRequest createFaucetAddressRequest
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createFaucetAddressUsingPOST(createFaucetAddressRequest: CreateFaucetAddressRequest, observe?: 'body', reportProgress?: boolean): Observable<UserAddress>;
    public createFaucetAddressUsingPOST(createFaucetAddressRequest: CreateFaucetAddressRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserAddress>>;
    public createFaucetAddressUsingPOST(createFaucetAddressRequest: CreateFaucetAddressRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserAddress>>;
    public createFaucetAddressUsingPOST(createFaucetAddressRequest: CreateFaucetAddressRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (createFaucetAddressRequest === null || createFaucetAddressRequest === undefined) {
            throw new Error('Required parameter createFaucetAddressRequest was null or undefined when calling createFaucetAddressUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<UserAddress>(`${this.basePath}/faucet/createFaucetAddress`,
            createFaucetAddressRequest,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets the faucet address balance
     * Gets the faucet address balance and returns it
     * @param faucetBalanceRequest faucetBalanceRequest
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getBalanceUsingPOST(faucetBalanceRequest: FaucetBalanceRequest, observe?: 'body', reportProgress?: boolean): Observable<UserAddress>;
    public getBalanceUsingPOST(faucetBalanceRequest: FaucetBalanceRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserAddress>>;
    public getBalanceUsingPOST(faucetBalanceRequest: FaucetBalanceRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserAddress>>;
    public getBalanceUsingPOST(faucetBalanceRequest: FaucetBalanceRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (faucetBalanceRequest === null || faucetBalanceRequest === undefined) {
            throw new Error('Required parameter faucetBalanceRequest was null or undefined when calling getBalanceUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<UserAddress>(`${this.basePath}/faucet/balance`,
            faucetBalanceRequest,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets the faucet address
     * Gets the faucet address and returns it
     * @param faucetUser faucetUser
     * @param faucetAddressRequest faucetAddressRequest
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFaucetAddressUsingPOST(faucetUser: boolean, faucetAddressRequest: FaucetAddressRequest, observe?: 'body', reportProgress?: boolean): Observable<UserAddress>;
    public getFaucetAddressUsingPOST(faucetUser: boolean, faucetAddressRequest: FaucetAddressRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserAddress>>;
    public getFaucetAddressUsingPOST(faucetUser: boolean, faucetAddressRequest: FaucetAddressRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserAddress>>;
    public getFaucetAddressUsingPOST(faucetUser: boolean, faucetAddressRequest: FaucetAddressRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (faucetUser === null || faucetUser === undefined) {
            throw new Error('Required parameter faucetUser was null or undefined when calling getFaucetAddressUsingPOST.');
        }
        if (faucetAddressRequest === null || faucetAddressRequest === undefined) {
            throw new Error('Required parameter faucetAddressRequest was null or undefined when calling getFaucetAddressUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<UserAddress>(`${this.basePath}/faucet/getFaucetAddress/${encodeURIComponent(String(faucetUser))}`,
            faucetAddressRequest,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get faucet list
     * Get faucet list and returns it
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFaucetListUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<UserAddress>>;
    public getFaucetListUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<UserAddress>>>;
    public getFaucetListUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<UserAddress>>>;
    public getFaucetListUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<UserAddress>>(`${this.basePath}/faucet/getFaucetList`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets the faucet address payments
     * Gets the faucet address payments and returns it
     * @param userAddress userAddress
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFaucetPaymentsUsingPOST(userAddress: UserAddress, observe?: 'body', reportProgress?: boolean): Observable<Array<FaucetAddressPayment>>;
    public getFaucetPaymentsUsingPOST(userAddress: UserAddress, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<FaucetAddressPayment>>>;
    public getFaucetPaymentsUsingPOST(userAddress: UserAddress, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<FaucetAddressPayment>>>;
    public getFaucetPaymentsUsingPOST(userAddress: UserAddress, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (userAddress === null || userAddress === undefined) {
            throw new Error('Required parameter userAddress was null or undefined when calling getFaucetPaymentsUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<Array<FaucetAddressPayment>>(`${this.basePath}/faucet/getFaucetAddressPayments`,
            userAddress,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Is the Service running ?
     * Returns if the service runs or not. Without other exceptions in mind, just running
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getResourceInfoUsingGET(observe?: 'body', reportProgress?: boolean): Observable<RestResourceInfo>;
    public getResourceInfoUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RestResourceInfo>>;
    public getResourceInfoUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RestResourceInfo>>;
    public getResourceInfoUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<RestResourceInfo>(`${this.basePath}/faucet/info`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Send a payment from the faucet
     * Send a payment from the faucet
     * @param address address
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public payoutUsingPOST(address: UserAddress, observe?: 'body', reportProgress?: boolean): Observable<ResultOk>;
    public payoutUsingPOST(address: UserAddress, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResultOk>>;
    public payoutUsingPOST(address: UserAddress, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResultOk>>;
    public payoutUsingPOST(address: UserAddress, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (address === null || address === undefined) {
            throw new Error('Required parameter address was null or undefined when calling payoutUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<ResultOk>(`${this.basePath}/faucet/payout`,
            address,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Send a payment from the faucet
     * Send a payment from the faucet
     * @param faucetPaymentRequest faucetPaymentRequest
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sendUsingPOST(faucetPaymentRequest: FaucetPaymentRequest, observe?: 'body', reportProgress?: boolean): Observable<FaucetPaymentRequest>;
    public sendUsingPOST(faucetPaymentRequest: FaucetPaymentRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<FaucetPaymentRequest>>;
    public sendUsingPOST(faucetPaymentRequest: FaucetPaymentRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<FaucetPaymentRequest>>;
    public sendUsingPOST(faucetPaymentRequest: FaucetPaymentRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (faucetPaymentRequest === null || faucetPaymentRequest === undefined) {
            throw new Error('Required parameter faucetPaymentRequest was null or undefined when calling sendUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<FaucetPaymentRequest>(`${this.basePath}/faucet/send`,
            faucetPaymentRequest,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update the faucet address
     * Update the faucet address and returns it
     * @param userAddress userAddress
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateFaucetAddressUsingPOST(userAddress: UserAddress, observe?: 'body', reportProgress?: boolean): Observable<UserAddress>;
    public updateFaucetAddressUsingPOST(userAddress: UserAddress, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserAddress>>;
    public updateFaucetAddressUsingPOST(userAddress: UserAddress, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserAddress>>;
    public updateFaucetAddressUsingPOST(userAddress: UserAddress, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (userAddress === null || userAddress === undefined) {
            throw new Error('Required parameter userAddress was null or undefined when calling updateFaucetAddressUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<UserAddress>(`${this.basePath}/faucet/updateFaucetAddress`,
            userAddress,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
