/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionInType } from './transactionInType';
import { TransactionOutType } from './transactionOutType';


export interface TransactionBlockWrapper {
    extra?: string;
    unlockTime?: number;
    version?: number;
    vin?: Array<TransactionInType>;
    vout?: Array<TransactionOutType>;
}
