/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressBalance } from './addressBalance';
import { ApiKeys } from './apiKeys';
import { UserAddressPK } from './userAddressPK';
import { WalletCoin } from './walletCoin';


export interface UserAddress {
    address?: string;
    apiKeys?: ApiKeys;
    balance?: AddressBalance;
    currency?: WalletCoin;
    faucet?: boolean;
    faucetPaidBalance?: AddressBalance;
    faucetUrl?: string;
    faucetUser?: boolean;
    groupName?: string;
    key?: UserAddressPK;
    name?: string;
    pairPk?: UserAddressPK;
    paymentId?: string;
    userId?: string;
}
